double* Alloc2D(int ni, int nj);
void Free2D(int ni, double* A);
double* Flat2D(int ni, int nj, double* A);
double* Mult(int ni, int nj, int nk, double* A, double* B);
void Mult_IP(int ni, int nj, int nk, double* A, double* B, double* C);
void Mult_DF_IP(int ni, int nj, int nk, double* A, double* B, double* C);
void Mult_FD_IP(int ni, int nj, int nk, double* A, double* B, double* C);
double* Tran(int ni, int nj, double* A);
void Tran_IP(int ni, int nj, double* A, double* B);
void Ax_b(int ni, int nj, double* A, double* x, double* b);
int Inv(double* A, double* Ainv, int n);
void Mult_IP_blas(int ni, int nj, int nk, double* A, double* B, double* C, double* _A, double* _B, double* _C);
