typedef double (ICfunc) (double* xi);

class M1DDSolve {
    public:
        M1DDSolve(Topo* _topo, Geom* _geom);
        ~M1DDSolve();
        int rank;
        GaussLobatto* quad;
        LagrangeNode* node;
        LagrangeEdge* edge;
        Wii* Q;
        M1x_j_xy_i* U;
        M1y_j_xy_i* V;
	double** Ut;
	double** Vt;
        Topo* topo;
        Geom* geom;
        Umat* M1;
        Wmat* M2;
        E21mat* EtoF;
        KSP ksp;           // 1 form mass matrix linear solver
        void init1(Vec u, ICfunc* func_x, ICfunc* func_y);
        void init2(Vec h, ICfunc* func);
        void err1(Vec u, ICfunc* fu, ICfunc* fv, ICfunc* fp, double* norms);
	Mat Mii;
	Mat Mid;
	Mat Mis;
	Mat Mdi;
	Mat Mdd;
	Mat Mds;
	Mat Msi;
	Mat Msd;
	Mat Mss;
	Mat Midid_inv;
	Mat Mid_s;
	Mat Mid_s_T;
	Mat Mi_ds;
	Mat Mi_ds_T;
	Mat Midid_inv_Mid_s;
	Mat Mii_inv;
	Mat Mii_inv_Mig;
	Mat Mgi_Mii_inv;
        Mat M0Rdual;
        Mat M0Rdual_T;
        Mat M0Rdual_Midid_inv_Mid_s;
        Mat M0Rdual_Midid_inv_M0Rdual_T;
	Mat Ss_l;
        Mat Ss;
        Mat Sg;
        Vec b_intl;
        Vec x_intl;
        Vec b_dual;
        Vec x_dual;
        Vec b_skel;
        Vec x_skel;
        Vec b_skel_g;
        Vec x_skel_g;
	void assemble_mat();
	void assemble_rhs_hu(Vec vel, Vec rho);
        void pack_intl_dual_sq();
        void pack_intl_dual_skel();
        void pack_schur_skel();
	void setup_matrices();
        void solve_F(Vec h, Vec ul);
};
